manual_export:
  name: Manual Export
  description: Export Home Assistant data to BigQuery for a specified time range
  fields:
    days_back:
      name: Days Back
      description: Number of days back to export (default 30)
      example: 7
      selector:
        number:
          min: 1
          max: 365
          mode: box
    start_time:
      name: Start Time
      description: Start time for export (ISO format, optional)
      example: "2024-01-01T00:00:00"
      selector:
        text:
    end_time:
      name: End Time
      description: End time for export (ISO format, optional) 
      example: "2024-01-02T00:00:00"
      selector:
        text:

incremental_export:
  name: Incremental Export
  description: Export new Home Assistant data since the last export